### ISSUE TITLE
List view expansion expands only on toggle click but entire row shows hand cursor

### ISSUE THREAD

**Issue by jeff-phillips-18** [patternfly/angular-patternfly#357] opened 2016-12-05 13:11 UTC
When setting the list view to include expanding rows the entire row gets the hand cursor but the click doesn't do anything unless it is on the expand toggle. In Patternfly examples clicking anywhere in the row expands the item (unless there is  a link, button, or kebab).

**Comment by dtaylor113** [comment] 2017-04-19 19:41
I cannot reproduce this in angular-patternfly v3.x.  With expanding rows, clicking anywhere in the row triggers the expansion open/close.  I believe this was fixed via PR #400

**Closed by dtaylor113** 2017-04-19 19:41 UTC
