### ISSUE TITLE
patternfly is not defined

### ISSUE THREAD

**Issue by Mirror198829** [patternfly/angular-patternfly#558] opened 2017-08-09 03:32 UTC
After flow the useage,<script> correct angular-patternfly, chrome console.warn("patternfly is not defined")。everyone meet this problem???

**Comment by cdcabrera** [comment] 2017-08-09 03:57
Angular PatternFly requires an additional JS script reference from [PatternFly](https://github.com/patternfly/patternfly) to work

If you're running locally you can do something like...

```html
<script src="node_modules/patternfly/dist/js/patternfly.js"></script>
<script src="node_modules/angular-patternfly/dist/angular-patternfly.js"></script>
```

[The ReadMe highlights some of the additional JS resources.](https://github.com/patternfly/angular-patternfly#using-angular-patternfly-in-your-application) like...

```html
<!-- Angular -->
<script src="node_modules/angular/angular.min.js"></script>

<!-- Angular-Bootstrap -->
<script src="node_modules/angular-ui-bootstrap/dist/ui-bootstrap.js"></script>
<script src="node_modules/angular-ui-bootstrap/dist/ui-bootstrap-tpls.js"></script>

<!-- Angular-Sanitize -->
<script src="node_modules/angular-sanitize/angular-sanitize.min.js"></script>

<!-- Angular-PatternFly  -->
<script src="node_modules/angular-patternfly/dist/angular-patternfly.min.js"></script>

<!-- C3, D3 - Charting Libraries. Only required if you are using the 'patternfly.charts' module-->
<script src="node_modules/patternfly/node_modules/c3/c3.min.js"></script>
<script src="node_modules/patternfly/node_modules/d3/d3.min.js"></script>
```

Related to PR #538

**Comment by Mirror198829** [comment] 2017-08-09 07:09
@cdcabrera   I have try both your replies .
1 solution shows following:  the "patternfly is not defined" has been solved,but when I "var app = angular.module('myApp',['ui.router','patternfly'])" ,then chorome console.error like "jquery.min.js:2 Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.5.11/$injector/modulerr?………………"
2 solution when I  pull in all scripts，then the same problem occured:'patternfly is not defined'

**Comment by cdcabrera** [comment] 2017-08-09 14:40
It sounds like you're looking for a more specific example, not code snippets, like above. Receiving console errors requesting resources means we probably need to locate them.

You can look in places like [NPM](https://www.npmjs.com/).Then look at updating ```package.json``` so you can download the resources with ```npm install```. Once that's complete, then a more complete example ***might*** look like...

```html
<!-- jQuery -->
<script src="node_modules/jquery/dist/jquery.min.js"></script>

<!-- PatternFly -->
<script src="node_modules/patternfly/dist/js/patternfly.min.js"></script>

<!-- Angular -->
<script src="node_modules/angular/angular.min.js"></script>

<!-- Angular-Bootstrap -->
<script src="node_modules/angular-ui-bootstrap/dist/ui-bootstrap.js"></script>
<script src="node_modules/angular-ui-bootstrap/dist/ui-bootstrap-tpls.js"></script>

<!-- Angular-Sanitize -->
<script src="node_modules/angular-sanitize/angular-sanitize.min.js"></script>

<!-- Angular-PatternFly  -->
<script src="node_modules/angular-patternfly/dist/angular-patternfly.min.js"></script>

<!-- C3, D3 - Charting Libraries. Only required if you are using the 'patternfly.charts' module-->
<script src="node_modules/patternfly/node_modules/c3/c3.min.js"></script>
<script src="node_modules/patternfly/node_modules/d3/d3.min.js"></script>
```

**Comment by cdcabrera** [comment] 2017-08-09 14:52
@Mirror198829 I'm going to close this since the provided response relates to implementation and not a bug or feature request. This issue does help highlight that we may need to update our ReadMe.

You can reopen the issue if you continue to have problems

**Closed by cdcabrera** 2017-08-09 14:52 UTC
Labels: question
