### ISSUE TITLE
Issue with using angular-bootstrap-prettify and keycloak.js adapter 

### ISSUE THREAD

**Issue by akoserwal** [patternfly/angular-patternfly#675] opened 2017-11-16 17:05 UTC
keycloak.js has this function called _decodeToken,_ .Which decodes the jwt token and works fine. 
  
  ```
   function decodeToken(str) {
          .......
            str = decodeURIComponent(escape(atob(str)));

            str = JSON.parse(str);
            return str;
        }
```
str would look like this

`str ="{"jti":"8d95f811-7e4b-4874-9b7c-4d9908e234","exp":151434601,"nbf":0,"iat":1510849601,"iss":"https://localhost/auth/realms/demo","aud":"productapp","sub"..,"resource_access":{"account":{"roles":["dsf","view-profile"]}}}"
`

Now this will jump to  _escape_ function in
[angular-bootstrap-prettify.js](https://www.patternfly.org/components/angular-patternfly/dist/docs/grunt-scripts/angular-bootstrap-prettify.js
)

```
function escape(text) {
  return text.
    replace(/\&/g, '&amp;').
    replace(/\</g, '&lt;').
    replace(/\>/g, '&gt;').
    replace(/"/g, '&quot;');
}
```

Which will replace " to &quot

`"{&quot;jti&quot;:&quot;85fa15e8-1435-47c5-833d-f15d77c79e22&quot;,&quot;exp&quot;:1510884333,&quot;nbf&quot;:0,&quot;iat&quot;:1510848333,&quot;iss&quot;:&quot;https://auth.dev.redhat.com/auth/realms/demoquot;,&quot;aud&quot;:&quot;performance-develop-jstest&quot;,&quot;sub&quot;:&quot;0203bd27-279b-47e1-916e-....&quot;]}}}"`

Now in keycloak.js (decodeToken) will fail to parse the str due to replace characters.
`    str = JSON.parse(str);`

**Comment by jeff-phillips-18** [comment] 2017-11-16 17:15
Looks like the issue is with including angular-bootstrap-prettify.js rather than an issue with angular-patternfly.

**Comment by akoserwal** [comment] 2017-11-16 18:01
@jeff-phillips-18: yeah, to be more correct. I saw  this #108 and #109. Is angular-bootstrap-prettify has been removed from the package?

**Comment by jeff-phillips-18** [comment] 2017-11-16 18:19
It is still in our docs area but that should not effect applications. Are you doing development in angular-patternfly? I will look into removing it from our docs area.

**Comment by akoserwal** [comment] 2017-11-16 18:52
@jeff-phillips-18: yes, we are using angular-patternfly for our application. thanks

**Comment by jeff-phillips-18** [comment] 2017-11-16 19:07
@akoserwal But why are you including https://www.patternfly.org/components/angular-patternfly/dist/docs/grunt-scripts/angular-bootstrap-prettify.js in your application?

**Comment by akoserwal** [comment] 2017-11-17 05:38
@jeff-phillips-18: Previous developer on this application was using this library. I think, we don't need this one. I removed it.

**Comment by jeff-phillips-18** [comment] 2017-11-17 19:09
OK @akoserwal, going to close this issue then.

**Closed by jeff-phillips-18** 2017-11-17 19:09 UTC
